<?php

$extensions = array(
	array(
		'name'			=>	'Affiliates &amp; Tracking',
		'link'			=>	"http://tribulant.com/extensions/view/1/affiliates-tracking",
		'description'	=>	"Easy 3rd party affiliate program and Google Analytics ecommerce clicks tracking and sales conversion for the WordPress Shopping Cart plugin.",
		'slug'			=>	'affiliates',
		'plugin_name'	=>	'checkout-affiliates',
		'plugin_file'	=>	'affiliates.php',
	),
	array(
		'name'			=>	'Amazon FPS Gateway',
		'link'			=>	"http://tribulant.com/extensions/view/12/amazon-fps-gateway",
		'description'	=>	"Amazon FPS payment gateway for payments through the WordPress Shopping Cart plugin.",
		'slug'			=>	'amazonfps',
		'plugin_name'	=>	'checkout-amazonfps',
		'plugin_file'	=>	'amazonfps.php',
	),
	array(
		'name'			=>	'APCO Limited Payment Gateway',
		'link'			=>	"http://tribulant.com/extensions/view/9/apco-limited",
		'description'	=>	"APCO Limited payment gateway for credit card payments while keeping your customers on your site.",
		'slug'			=>	'apco',
		'plugin_name'	=>	'checkout-apco',
		'plugin_file'	=>	'apco.php',
	),
	array(
		'name'			=>	'BluePay 2.0 Redirect Payment Gateway',
		'link'			=>	"http://tribulant.com/extensions/view/5/bluepay-payment-gateway",
		'description'	=>	"BluePay 2.0 Redirect payment gateway interface for the Shopping Cart plugin.",
		'slug'			=>	"bluepay",
		'plugin_name'	=>	"checkout-bluepay",
		'plugin_file'	=>	"bluepay.php",
	),
	array(
		'name'			=>	'Echo Global Logistics',
		'link'			=>	"http://tribulant.com/extensions/",
		'description'	=>	"Calculate shipping services/rates for customers in real time with Echo Global Logistics.",
		'slug'			=>	"echo",
		'plugin_name'	=>	"checkout-echo",
		'plugin_file'	=>	"echo.php",
	),
	array(
		'name'			=>	'EU VAT Exemption',
		'link'			=>	"http://tribulant.com/extensions/view/13/eu-vat-exemption",
		'description'	=>	"Exempt order VAT from customers with a valid, registered EU VAT number.",
		'slug'			=>	'euvatex',
		'plugin_name'	=>	'checkout-euvatex',
		'plugin_file'	=>	'euvatex.php',
	),
	array(
		'name'			=>	'First Data API',
		'link'			=>	"http://tribulant.com/extensions/view/7/first-data-api",
		'description'	=>	"First Data Global Gateway API protocol extension to keep customers on your site while processing their credit card.",
		'slug'			=>	'fdapi',
		'plugin_name'	=>	'checkout-fdapi',
		'plugin_file'	=>	'fdapi.php',
	),
	array(
		'name'			=>	'Guest Checkout',
		'link'			=>	"http://tribulant.com/extensions/",
		'description'	=>	"Guest checkout to eliminate the required user registration during checkout.",
		'slug'			=>	'guest',
		'plugin_name'	=>	'checkout-guest',
		'plugin_file'	=>	'guest.php',
	),
	array(
		'name'			=>	'iPay88 Payment Gateway',
		'link'			=>	"http://tribulant.com/extensions/view/8/ipay88-payment-gateway",
		'description'	=>	"iPay88 payment gateway interface for the Shopping Cart plugin.",
		'slug'			=>	'ipay',
		'plugin_name'	=>	'checkout-ipay',
		'plugin_file'	=>	'ipay.php',
	),
	array(
		'name'			=>	'Netcash Payment Gateway',
		'link'			=>	"http://tribulant.com/extensions/view/2/netcash-payment-gateway",
		'description'	=>	"South African Netcash payment gateway extension for the Shopping Cart plugin to accept credit card payments.",
		'slug'			=>	'netcash',
		'plugin_name'	=>	'checkout-netcash',
		'plugin_file'	=>	'netcash.php',
	),
	array(
		'name'			=>	'Newsletters Subscribers',
		'link'			=>	"http://tribulant.com/extensions/",
		'description'	=>	"Capture subscribers into the Newsletter plugin from new customers.",
		'slug'			=>	'newsletters',
		'plugin_name'	=>	'checkout-newsletters',
		'plugin_file'	=>	'newsletters.php',
	),
	array(
		'name'			=>	'One Click SSL',
		'link'			=>	"http://tribulant.com/extensions/view/15/one-click-ssl",
		'description'	=>	"One click https:// (SSL) capability in your shop and checkout procedure.",
		'slug'			=>	'ssl',
		'plugin_name'	=>	'checkout-ssl',
		'plugin_file'	=>	'ssl.php',
	),
	array(
		'name'			=>	'SagePay Form Protocol Payment Gateway',
		'link'			=>	"http://tribulant.com/extensions/view/3/sagepay-form-protocol-gateway",
		'description'	=>	"SagePay form protocol payment gateway for credit card payments from your customers through the Shopping Cart plugin.",
		'slug'			=>	'sagepay',
		'plugin_name'	=>	'checkout-sagepay',
		'plugin_file'	=>	'sagepay.php',
	),
	array(
		'name'			=>	'SecureTrading Payment Pages',
		'link'			=>	"http://tribulant.com/extensions/view/11/securetrading-payment-pages",
		'description'	=>	"SecureTrading Payment Pages payment gateway for credit card payments from your customers through the Shopping Cart plugin.",
		'slug'			=>	'securetrading',
		'plugin_name'	=>	'checkout-securetrading',
		'plugin_file'	=>	'securetrading.php',
	),
	'stripe' => array(
		'name'			=>	'Stripe Payment Gateway',
		'link'			=>	"http://tribulant.com/extensions/view/10/stripe-payment-gateway",
		'description'	=>	"Stripe payment gateway for credit card payments from your customers through the Shopping Cart plugin.",
		'slug'			=>	'stripe',
		'plugin_name'	=>	'checkout-stripe',
		'plugin_file'	=>	'stripe.php',
	),
	array(
		'name' 			=> 	'Zoom Gallery',
		'link'			=>	"http://tribulant.com/extensions/view/4/zoom-gallery",
		'description'	=>	"Create beautiful, user-friendly image galleries on products with a zoom effect on hover to eliminate any clicking or refreshing.",
		'slug'			=>	'jqzoom',
		'plugin_name'	=>	'checkout-jqzoom',
		'plugin_file'	=>	'jqzoom.php',
	),
);

?>