<div class="tribulant_plugin_tabs">
	<ul>
    	<?php if (current_user_can('checkout_settings')) : ?><li <?php echo ($_GET['page'] == $this -> sections -> settings) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo $this -> sections -> settings; ?>" title="<?php _e('General', $this -> plugin_name); ?>"><?php _e('General', $this -> plugin_name); ?></a><span class="border-right"></span></li><?php endif; ?>
        <?php if (current_user_can('checkout_settings_products')) : ?><li <?php echo ($_GET['page'] == $this -> sections -> settings_products) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo $this -> sections -> settings_products; ?>" title="<?php _e('Products &amp; Images', $this -> plugin_name); ?>"><?php _e('Products &amp; Images', $this -> plugin_name); ?></a><span class="border-right"></span></li><?php endif; ?>
        <?php if (current_user_can('checkout_settings_taxshipping')) : ?><li <?php echo ($_GET['page'] == $this -> sections -> settings_taxshipping) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo $this -> sections -> settings_taxshipping; ?>" title="<?php _e('Calculations', $this -> plugin_name); ?>"><?php _e('Calculations', $this -> plugin_name); ?></a><span class="border-right"></span></li><?php endif; ?>
        <?php if (current_user_can('checkout_settings_pmethods')) : ?><li <?php echo ($_GET['page'] == $this -> sections -> settings_pmethods) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo $this -> sections -> settings_pmethods; ?>" title="<?php _e('Payment Methods', $this -> plugin_name); ?>"><?php _e('Payment Methods', $this -> plugin_name); ?></a><span class="border-right"></span></li><?php endif; ?>
        <?php if (current_user_can('checkout_settings_paymentfields')) : ?><li <?php echo ($_GET['page'] == $this -> sections -> settings_paymentfields) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo $this -> sections -> settings_paymentfields; ?>" title="<?php _e('Payment Fields', $this -> plugin_name); ?>"><?php _e('Payment Fields', $this -> plugin_name); ?></a><span class="border-right"></span></li><?php endif; ?>
        <?php if (current_user_can('checkout_settings_invoice')) : ?><li <?php echo ($_GET['page'] == $this -> sections -> settings_invoice) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo $this -> sections -> settings_invoice; ?>" title="<?php _e('Invoices', $this -> plugin_name); ?>"><?php _e('Invoices', $this -> plugin_name); ?></a><span class="border-right"></span></li><?php endif; ?>
        <?php if ($this -> is_plugin_active('affiliates')) : ?>
        	<?php if (current_user_can('checkout_settings_affiliates')) : ?><li <?php echo ($_GET['page'] == $this -> sections -> settings_affiliates) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo $this -> sections -> settings_affiliates; ?>" title="<?php _e('Tracking', $this -> plugin_name); ?>"><?php _e('Tracking', $this -> plugin_name); ?></a><span class="border-right"></span></li><?php endif; ?>
        <?php endif; ?>
    </ul>
    
    <br style="display:block; width:100%; clear:both; visibility:hidden;" />
</div>